# -*- coding: utf-8 -*-
"""HelloColab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaetFwSqgGc1toB4hthp5RgkWY-bbcQG
"""

print("Hello colab!")

